version: "3.9"
services:
  mysql_builder:
    image: mysql:8.0.35
    container_name: PaperlessMySQL
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
      - 13306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: 'account'
      MYSQL_ROOT_PASSWORD: admin!
    volumes:
      - ./src/test/resources/mysql/initdb.d:/docker-entrypoint-initdb.d

  redis_builder:
    image: redis:6.2.6-alpine
    container_name: PaperlessRedis
    ports:
      - 16379:6379
    command:
      - redis-server
    restart: always